<?php

//use App\Mail;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('contact',function(){

	return view('contact');
});


Route::get('about',function(){

	return view('about');
});

Route::get('welcome-email',function(){
//Findings

	//How to set up emailing using mail trap.
	//Make account on mail trap and get values for .env , put in .env 
	//Then make mailable for a specific email, what is mailable?
	//It is an email sending class which can be generated by artisan command.
	//run php artisan make:mail WelcomeEmail
	//Need to make view for email and set in WelcomeEmail. like 
	// in build funciton change return $this->view('view.email'); to  return $this->view('emails.welcome'); or according to your email view. 

	//At first I put following line here.

	//Mail::to('malik.adeel.ks@gmail.com')->send(new WelcomeEmail);

	//issue raised so I modified to

	//Mail::to('malik.adeel.ks@gmail.com')->send(new App\Mail\WelcomeEmail);

	//but another issue raised. then I change mail.php and modified default values according to .env. then run followin commands.

	//php artisan cache:clear

	//php artisan config:cache

	Mail::to('malik.adeel.ks@gmail.com')->send(new App\Mail\WelcomeEmail);


});